/**
 * Hand-curated example fire perimeters used by the playground.
 *
 * Sizes are deliberately within the bulk of the model's TRAINING distribution
 * (p50 = 0.7 ha, p75 = 25 ha, p95 = 220 ha). The earlier 4000+ ha polygons
 * were ~20× the 95th percentile, which pushed every feature 300+ standard
 * deviations out-of-support and made the U-Net's output collapse to zero.
 *
 * Geometry is generated by `backend/scripts/gen_examples.py`. Each polygon is
 * a slightly-rotated regular hexagon centred at a known Uruguayan location,
 * sized to a real area in hectares. Coordinates are [lon, lat] in WGS84.
 */

export type ExampleFire = {
  id: string;
  name: { es: string; en: string };
  area_ha_estimate: number;
  scenario_id: string;
  geometry: GeoJSON.Polygon;
};

export const EXAMPLE_FIRES: ExampleFire[] = [
  {
    id: "artigas-pinares",
    name: { es: "Pinares · Artigas", en: "Pine plantations · Artigas" },
    area_ha_estimate: 35,
    scenario_id: "verano_seco_norte",
    geometry: {
      type: "Polygon",
      coordinates: [[
        [-56.616296, -30.429144], [-56.619007, -30.426806], [-56.622712, -30.427662],
        [-56.623704, -30.430856], [-56.620993, -30.433194], [-56.617288, -30.432338],
        [-56.616296, -30.429144],
      ]],
    },
  },
  {
    id: "salto-norte",
    name: { es: "Bañado · Salto", en: "Salto wetlands" },
    area_ha_estimate: 80,
    scenario_id: "verano_seco_norte",
    geometry: {
      type: "Polygon",
      coordinates: [[
        [-57.294356, -31.173706], [-57.298488, -31.170171], [-57.304132, -31.171465],
        [-57.305644, -31.176294], [-57.301512, -31.179829], [-57.295868, -31.178535],
        [-57.294356, -31.173706],
      ]],
    },
  },
  {
    id: "tacuarembo-norte",
    name: { es: "Eucaliptus · Tacuarembó", en: "Eucalyptus · Tacuarembó" },
    area_ha_estimate: 150,
    scenario_id: "pampero_intenso",
    geometry: {
      type: "Polygon",
      coordinates: [[
        [-55.882232, -31.658228], [-55.887919, -31.653388], [-55.895687, -31.65516],
        [-55.897768, -31.661772], [-55.892081, -31.666612], [-55.884313, -31.66484],
        [-55.882232, -31.658228],
      ]],
    },
  },
  {
    id: "durazno-centro",
    name: { es: "Sierras de Durazno", en: "Durazno hills" },
    area_ha_estimate: 100,
    scenario_id: "pampero_intenso",
    geometry: {
      type: "Polygon",
      coordinates: [[
        [-56.488563, -32.988553], [-56.493275, -32.984601], [-56.499712, -32.986048],
        [-56.501437, -32.991447], [-56.496725, -32.995399], [-56.490288, -32.993952],
        [-56.488563, -32.988553],
      ]],
    },
  },
  {
    id: "florida-pradera",
    name: { es: "Pradera · Florida", en: "Florida grasslands" },
    area_ha_estimate: 50,
    scenario_id: "verano_seco_norte",
    geometry: {
      type: "Polygon",
      coordinates: [[
        [-56.130401, -33.888977], [-56.133768, -33.886182], [-56.138367, -33.887205],
        [-56.139599, -33.891023], [-56.136232, -33.893818], [-56.131633, -33.892795],
        [-56.130401, -33.888977],
      ]],
    },
  },
  {
    id: "treinta-y-tres",
    name: { es: "Quebrada de los Cuervos", en: "Quebrada de los Cuervos" },
    area_ha_estimate: 251,
    scenario_id: "verano_seco_norte",
    geometry: {
      type: "Polygon",
      coordinates: [[
        [-54.424796, -33.222713], [-54.432266, -33.216464], [-54.44247, -33.218751],
        [-54.445204, -33.227287], [-54.437734, -33.233536], [-54.42753, -33.231249],
        [-54.424796, -33.222713],
      ]],
    },
  },
  {
    id: "maldonado-sierra",
    name: { es: "Sierra de las Ánimas", en: "Sierra de las Ánimas" },
    area_ha_estimate: 120,
    scenario_id: "pampero_intenso",
    geometry: {
      type: "Polygon",
      coordinates: [[
        [-55.257803, -34.733415], [-55.263072, -34.729086], [-55.270268, -34.730671],
        [-55.272197, -34.736585], [-55.266928, -34.740914], [-55.259732, -34.739329],
        [-55.257803, -34.733415],
      ]],
    },
  },
  {
    id: "rocha-costa",
    name: { es: "Costa de Rocha", en: "Rocha coast" },
    area_ha_estimate: 25,
    scenario_id: "verano_seco_norte",
    geometry: {
      type: "Polygon",
      coordinates: [[
        [-53.921727, -34.429277], [-53.924123, -34.427301], [-53.927396, -34.428024],
        [-53.928273, -34.430723], [-53.925877, -34.432699], [-53.922604, -34.431976],
        [-53.921727, -34.429277],
      ]],
    },
  },
];
